/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javaFXFrame;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.layout.*;
import javafx.scene.paint.Color;
import javafx.stage.Stage;

public class App extends Application {
    private final BorderPane root = new BorderPane();
    private final Scene scene = new Scene(root);
    private final HBox controls = new HBox(7.5);
    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage stage) {
        stage.setScene(scene);

        root.setStyle(root.getStyle() + "-fx-padding: 10 10 10 10;-fx-background: rgb(12,12,12);");
        root.setTop(controls);
        root.setCenter(new Label("test"));

        var minimize = new WindowControlButton(15,Color.valueOf("0xBA7816"),stage);
        var maximize = new WindowControlButton(15,Color.valueOf("0x518150"),stage);
        var close = new WindowControlButton(15,Color.valueOf("0xB54747"),stage);

        controls.getChildren().addAll(close,minimize,maximize);
        stage.setHeight(460);
        stage.setWidth(640);
        UndecoratedApplicationWindow.initializeAndShow(stage,scene,minimize,maximize,close);
    }
}
